Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1314, in _main
    main()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1049, in main
    esp.hard_reset()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/esptool/targets/esp32s3.py", line 386, in hard_reset
    HardReset(self._port, uses_usb_otg)()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/esptool/reset.py", line 46, in __call__
    self.port.open()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 336, in open
    self._update_dtr_state()
  File "/home/wish/.espressif/python_env/idf5.3_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 715, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/wish/.espressif/python_env/idf5.3_py3.12_env/bin/python;;/media/wish/Disk/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



